# Generated by Django 2.0 on 2017-12-10 11:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='remain_date',
            field=models.FloatField(default=0.0, verbose_name='남은 일수'),
        ),
    ]
