# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-06 15:27
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='VacationRequest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.PositiveSmallIntegerField(choices=[(0, '정기 휴가'), (1, '병가'), (2, '출산휴가'), (3, '경조사 휴가(결혼, 장례, 기타)'), (4, '무급 휴가')], verbose_name='휴가 타입')),
                ('start_date', models.DateTimeField(verbose_name='휴가 시작일')),
                ('end_date', models.DateTimeField(verbose_name='휴가 종료일')),
                ('using_date', models.FloatField(verbose_name='사용 일수')),
                ('status', models.PositiveSmallIntegerField(choices=[(0, '신청'), (1, '승인'), (2, '기각')], default=0, verbose_name='상태')),
                ('approver', models.CharField(max_length=16, verbose_name='승인자')),
                ('reason', models.TextField(verbose_name='사유')),
                ('document', models.FileField(upload_to='documents/%Y/%m/%d/')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vacation_request_set', related_query_name='vacation_request', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
